"""update models for password-reset

Revision ID: 3f7404553ba9
Create Date: 2026-01-18 06:47:11.707887
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f7404553ba9'
down_revision = 'b2d2353897de'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please review ###
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please review ###
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
    # ### end Alembic commands ###
